### ISSUE TITLE
Skipping user input?

### ISSUE THREAD

**Issue by Unuma-AN** [nickrallison/obsidian-note-linker-with-previewer#3]
Would be possible to add a button to "accept all" the changes made while linking a single note.
This would make it easier to use the plugin on longer documents where the user is certain that the document is formatted correctly and won't link false-positives.

**Comment by nickrallison** [comment]
I was hesitant but I think it needs to be done. I'll get working on it

**Comment by nickrallison** [comment]
I added a button, I wanted to get it to highlight all of the matches so they can be seen but it would need a good bit of refactoring.

For now "accept all" & "decline all" seem to work for me, if they don't, then please open another issue
